### ISSUE TITLE
Ran Example and got an error

### ISSUE THREAD

**Issue by jzicker** [johnmyleswhite/TextRegression#1]
library(TextRegression)
> text <- c('saying text is good',
+           'saying text once and saying text twice is better',
+           'saying text text text is best',
+           'saying text once is still ok',
+           'not saying it at all is bad',
+           'because text is a good thing',
+           'we all like text',
+           'even though sometimes it is missing')
> y <- c(1, 2, 3, 1, 0, 1, 1, 0)
> results <- regress.text(text, y)
Error in inherits(x, "Source") : 
  all(!is.na(match(c("doc_id", "text"), names(x)))) is not TRUE

**Comment by johnmyleswhite** [comment]
I suspect this package no longer works. I'd work with the more active parts of the R ecosystem instead.
